[package]
name = "satelit-scheduler"
version = "0.1.0"
authors = ["Igor Nikitin <rabbitinspace@icloud.com>"]
edition = "2018"

[dependencies]
tower-grpc = "0.1.0"
tower-hyper = "0.1.0"

prost = "0.5.0"
bytes = "0.4.12"
