[db]
url = "postgres://test:qwerty@localhost/scheduler"
max_connections = 16
connection_timeout = 10

[service.indexer]
url = "http://127.0.0.1:8080"
connection_timeout = 60 # 1 min
request_timeout = 60    # 1 min

[service.import]
url = "http://127.0.0.1:9060"
connection_timeout = 60 # 1 min
request_timeout = 3600  # 1 hour

[service.scraper]
url = "http://127.0.0.1:9050"
connection_timeout = 60 # 1 min
request_timeout = 3600  # 1 hour
