[anidb]
dump_url = "http://anidb.net/api/anime-titles.xml.gz"
download_path = "static/anidb_dump_next.gz"
serve_path = "static/anidb_dump.gz"
reimport_path = "static/reimports.json"

[service.import]
host = "127.0.0.1"
port = 10601

[service.task]
host = "127.0.0.1"
port = 10602

[service.scraper]
host = "127.0.0.1"
port = 10603
