[db]
url = "postgres://test:qwerty@localhost/scheduler"
max_connections = 16
connection_timeout = 10

[service.indexer]
anidb_url = "http://indexer.shitty.moe/index/anidb"
connection_timeout = 60    # 1 min

[service.import]
url = "http://import.shitty.moe"
request_timeout = 3600  # 1 hour

[service.scraper]
url = "http://scraper.shitty.moe"
request_timeout = 3600  # 1 hour
