[db]
url = "postgres://postgres:postgres@localhost/satelit-scheduler"
max_connections = 16
connection_timeout = 10

[services.indexer]
url = "http://127.0.0.1:8080"
connection_timeout = 60 # 1 min
request_timeout = 60    # 1 min

[services.import]
url = "http://127.0.0.1:9060"
connection_timeout = 60 # 1 min
request_timeout = 3600  # 1 hour

[services.scraper]
url = "http://127.0.0.1:9050"
connection_timeout = 60 # 1 min
request_timeout = 3600  # 1 hour

[index_url]
latest = "{base}/latest/{source}"
index_file = "{base}/index/{hash}"
