[db]
{{ if db }}
# PG_DB_URL
url = "{ db.url }"
{{ else }}
url = "postgres://postgres@localhost/satelit_scheduler"
{{ endif }}

max_connections = 16
connection_timeout = 10

[services.indexer]
# ST_INDEXER_URL
url = {{ if service_urls }}"{ service_urls.indexer }"{{ else }}"http://127.0.0.1:8080"{{ endif }}
connection_timeout = 60 # 1 min
request_timeout = 60    # 1 min

[services.import]
# ST_IMPORT_URL
url = {{ if service_urls }}"{ service_urls.import }"{{ else }}"http://127.0.0.1:9060"{{ endif }}
connection_timeout = 60 # 1 min
request_timeout = 3600  # 1 hour

[services.scraper]
# ST_SCRAPER_URL
url = {{ if service_urls }}"{ service_urls.scraper }"{{ else }}"http://127.0.0.1:9050"{{ endif }}
connection_timeout = 60 # 1 min
request_timeout = 3600  # 1 hour
